### PR TITLE
Add follow & unfollow. Closes #80

### LINKED ISSUE #80: Follow & unfollow profile
**User story**
As a Hypergraph user
I want to be able to follow a profile
so that I can stay up to date with that person's content

**Workflow**
- [x] Code
- [ ] Test

**Acceptance criteria**
- `p2pcommons.follows` metadata can be manipulated by the module's owner by adding or removing valid Dat archive keys (see [specs](https://github.com/p2pcommons/specs/blob/master/module.md#keyvalues))
- `p2pcommons.follows` may only be manipulated on profile modules
- `p2pcommons.follows` may only refer to profile modules
- `p2pcommons.follows` may be versioned

### PR DESCRIPTION
**Pull request by juliangruber**
Closes #80.

## TODO

- [x] refactor actions syntax
- [x] Add `--help` to both actions

### CODE REVIEW

**Comment by juliangruber** [comment]
> The version number is displayed next to the unfollowed profile name as well, rather than my own profile name.

That's expected behavior, since you're interested in the version of who you followed / unfollowed rather than your own version number. I've changed it so that for both `follow` and `unfollow` we print the `(vERSION)` _iff_ you followed a specific version, instead of an unversioned profile url.

**Comment by juliangruber** [comment]
dang I shouldn't have merged in master after requesting the review, will fix!

**Comment by juliangruber** [comment]
@jameslibscie The problem is actually that the sdk made a breaking schema change, so you'll have to delete `$HOME/.p2pcommons` and start with a fresh set of data.

**Comment by juliangruber** [comment]
> If I follow a versioned profile `hypergraph follow 5a49a02c429749a0318c3f3188deba7561b7f7a2884c3a4af32deb73caf392c1+11`, then I can unfollow that profile by specifying an unversioned profile `hypergraph unfollow 5a49a02c429749a0318c3f3188deba7561b7f7a2884c3a4af32deb73caf392c1` or a different version `hypergraph unfollow 5a49a02c429749a0318c3f3188deba7561b7f7a2884c3a4af32deb73caf392c1+12`. I think unfollow should have to match the version, but I'm guessing that's an SDK issue?

You're right, this looks to be an SDK issue.

> If I unfollow a profile that I am not currently following, it is also confirmed that I stopped following that profile, when actually nothing has happened. Is this in the SDK or CLI?

Either or. We can detect and warn about this in the CLI, but we could also fix it at the source and make the SDK throw an error here (preferred).

**Comment by juliangruber** [comment]
> @jameslibscie The problem is actually that the sdk made a breaking schema change, so you'll have to delete `$HOME/.p2pcommons` and start with a fresh set of data.

This is another reason why I strongly think we shouldn't advertise the CLI yet. We aren't warning about this anywhere.

**Comment by jameslibscie** [comment]
Basically `follow` seems to be missing an interactive mode. It somehow makes sense not to have one, as there's nothing interactive you can do with it, but that also means that selecting `Follow a profile` from the main `hypergraph` interactive mode doesn't work.

**Comment by juliangruber** [comment]
Great catch! I added interactive mode, it now asks for the profile url

**Pull request merged**
