### PR TITLE
Change update syntax. #87

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by jameslibscie** [comment]
I've updated #87 to limit the scope, so merging this PR may close #87.

**Comment by juliangruber** [comment]
> 1. Now that we can remove subtype using `hypergraph update [key] -s`, I've noticed that `hypergraph read` displays the subtype incorrectly if it's empty: it displays `Profile` instead of nothing. `subtype` is not mandatory btw (at least as far as the p2pcommons specs go), so it's OK that we can remove it.

fixed in #master

**Comment by juliangruber** [comment]
> 2\. I can't set a versioned parent using -p, it always sets the unversioned link as parent. Is this an SDK issue or a CLI issue? I've tried putting the whole link in quotes and it doesn't make a difference.

Create catch! Fixed :)

**Comment by juliangruber** [comment]
> I think working on Desktop is more important now btw than solving these issues, so if you want to get cracking, let me know and I will split these off into new issues and approve this one.

I'm looking forward to working on Desktop, and was luckily able to resolve the 2 requests in a timely manner. I would also like to finish this first, if any other requests come up.

**Comment by jameslibscie** [comment]
Just to clarify, the above should indeed generate an error, but not a stack trace IMO :)

**Comment by jameslibscie** [comment]
I'm actually also thinking that it should be explicitly stated in `hypergraph update --help` that `parents` is only for content modules.

```
PS D:\Websites\hypergraph-xyz\cli> hypergraph update --help

  Usage
    $ hypergraph update [hash]

  Command options
    --title, -t                             A content module's title
    --name, -n                              A profile module's name
    --subtype, -s                           WikiData identifier
    --description, -d                       Module description
    --parent, -p                            Module parent(s) -> A content module's parent(s)
    --main, -m                              Path to main file
```

Also, is it currently possible to add multiple parents in this way? If not, it should just say "parent" instead of "parent(s)"

**Comment by juliangruber** [comment]
> If I recall correctly, this needs fixing in the SDK, right?

Correct, the sdk should throw a `ValidationError` for this, then the CLI can handle it

**Comment by juliangruber** [comment]
> I'm actually also thinking that it should be explicitly stated in `hypergraph update --help` that `parents` is only for content modules.

Fixed

> Also, is it currently possible to add multiple parents in this way? If not, it should just say "parent" instead of "parent(s)"

Yes it is! `--parent FOO --parent BAR` works. I've added an example for this

**Pull request merged**
